apiVersion: v1
kind: Pod
metadata:
  name: multi-service-pod
spec:
  volumes:
    - name: log-volume
      emptyDir: {}
  initContainers:
    - name: init-log
      image: busybox
      command: ["sh","-c","mkdir -p /logs && touch /logs/app.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /logs

  containers:
    - name: app-container
      image: spring_app:latest
      imagePullPolicy: Never       # ← не пытаться тянуть образ
      args: ["--logging.file.name=/logs/app.log"]
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: log-volume
          mountPath: /logs

    - name: log-collector
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh","-c"]
      args:
        - |
          echo "Ждём появления лога…";
          until [ -s /logs/app.log ]; do sleep 1; done;
          tail -n+1 -f /logs/app.log
      volumeMounts:
        - name: log-volume
          mountPath: /logs
